// site-config.js — generated by admin. Do not hand-edit.
// admin password change + visitor password gate are managed from /admin.html.
window.SITE_CONFIG = {
  // SHA-256 of admin password. Default password: "leena2026"
  adminHash: "b3986620b18f97e4a9a3ac0fedd64ae3967791a63662f9caf07ac2b3f76bcc83",
  // Set true to require visitors to enter a password before they can view the portfolio.
  visitorProtect: false,
  // SHA-256 of visitor password (only used when visitorProtect is true).
  visitorHash: ""
};
