// site-config.js — generated by admin. Do not hand-edit.
window.SITE_CONFIG = {
  adminHash: "57255a315f15b7bc55ba4d248b849ee183b60da951b011ab40eae1f102297756",
  visitorProtect: false,
  visitorHash: ""
};
